In [14]:
import pandas as pd

route = "/Users/fangsiyu/Desktop/sdu-2026-code/805_multivariate_statistical_analysis/team_project/all_pathways_results_10000.csv"
df = pd.read_csv(route)

In [15]:
# GSEA_pvalue <= 0.05
print("the pathway that pass GSEA_pvalue: ", len(df[df['GSEA_pvalue'] <= 0.05]))
df[df['GSEA_pvalue'] <= 0.05]

the pathway that pass GSEA_pvalue:  8

                               Pathway    Max_ES  GSEA_pvalue  T2_pvalue
1         HALLMARK_ALLOGRAFT_REJECTION -0.639618       0.0061   0.002886
10                 HALLMARK_COMPLEMENT -0.414437       0.0436   0.240628
22        HALLMARK_IL2_STAT5_SIGNALING -0.410772       0.0093   0.010991
23    HALLMARK_IL6_JAK_STAT3_SIGNALING -0.572883       0.0027   0.004683
24      HALLMARK_INFLAMMATORY_RESPONSE -0.507190       0.0123   0.269030
26  HALLMARK_INTERFERON_GAMMA_RESPONSE -0.622360       0.0277   0.177217
28          HALLMARK_KRAS_SIGNALING_UP -0.396675       0.0325   0.021777
44    HALLMARK_TNFA_SIGNALING_VIA_NFKB -0.497607       0.0229   0.050620

In [16]:
# T2_pvalue <= 0.05
print("the pathway that pass T2_p_value: ", len(df[df['T2_pvalue'] <= 0.05]))
df[df['T2_pvalue'] <= 0.05]

the pathway that pass T2_p_value:  34

                                     Pathway    Max_ES  GSEA_pvalue  T2_pvalue
0                      HALLMARK_ADIPOGENESIS  0.140921       0.9915   0.009484
1               HALLMARK_ALLOGRAFT_REJECTION -0.639618       0.0061   0.002886
2                 HALLMARK_ANDROGEN_RESPONSE  0.215851       0.6307   0.009339
3                      HALLMARK_ANGIOGENESIS  0.339709       0.3725   0.003811
4                   HALLMARK_APICAL_JUNCTION -0.340239       0.0833   0.011741
5                    HALLMARK_APICAL_SURFACE -0.350776       0.1753   0.008937
6                         HALLMARK_APOPTOSIS -0.276762       0.1850   0.003044
11                       HALLMARK_DNA_REPAIR  0.354455       0.0763   0.000288
12                      HALLMARK_E2F_TARGETS  0.357506       0.4494   0.006782
14          HALLMARK_ESTROGEN_RESPONSE_EARLY  0.242590       0.5770   0.001002
15           HALLMARK_ESTROGEN_RESPONSE_LATE -0.171938       0.9092   0.044917
17                   HALLMARK_G2M_CHECKPOINT  0.293459       0.5061   0.000512
18                       HALLMARK_GLYCOLYSIS  0.174931       0.8944   0.011455
19               HALLMARK_HEDGEHOG_SIGNALING -0.327190       0.2904   0.037204
20                  HALLMARK_HEME_METABOLISM -0.234262       0.2387   0.034120
21                          HALLMARK_HYPOXIA -0.284107       0.2652   0.011225
22              HALLMARK_IL2_STAT5_SIGNALING -0.410772       0.0093   0.010991
23          HALLMARK_IL6_JAK_STAT3_SIGNALING -0.572883       0.0027   0.004683
25        HALLMARK_INTERFERON_ALPHA_RESPONSE -0.621516       0.0809   0.015010
28                HALLMARK_KRAS_SIGNALING_UP -0.396675       0.0325   0.021777
29                  HALLMARK_MITOTIC_SPINDLE -0.201958       0.6946   0.003735
31                   HALLMARK_MYC_TARGETS_V1  0.175868       0.9062   0.026083
34                  HALLMARK_NOTCH_SIGNALING  0.224445       0.8137   0.000485
37              HALLMARK_PANCREAS_BETA_CELLS -0.196180       0.9295   0.004411
38                       HALLMARK_PEROXISOME  0.181207       0.9031   0.000019
39          HALLMARK_PI3K_AKT_MTOR_SIGNALING -0.335329       0.0586   0.003357
40                HALLMARK_PROTEIN_SECRETION  0.397420       0.0740   0.000721
41  HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY -0.219764       0.7656   0.013921
42                  HALLMARK_SPERMATOGENESIS  0.222677       0.6395   0.000614
43               HALLMARK_TGF_BETA_SIGNALING -0.305482       0.4126   0.001740
45        HALLMARK_UNFOLDED_PROTEIN_RESPONSE -0.237909       0.5439   0.000384
46                   HALLMARK_UV_RESPONSE_DN -0.254590       0.4441   0.022124
48       HALLMARK_WNT_BETA_CATENIN_SIGNALING -0.319926       0.3771   0.002231
49            HALLMARK_XENOBIOTIC_METABOLISM -0.245207       0.3038   0.002650

In [17]:
# the pathway got inconsistent, only GSEA_pvalue pass the 0.05
print("those pathways that only pass GSEA_pvalue: ", len(df[(df['GSEA_pvalue'] <= 0.05) & (df['T2_pvalue'] >= 0.05)]))
df[(df['GSEA_pvalue'] <= 0.05) & (df['T2_pvalue'] >= 0.05)]

those pathways that only pass GSEA_pvalue:  4

                               Pathway    Max_ES  GSEA_pvalue  T2_pvalue
10                 HALLMARK_COMPLEMENT -0.414437       0.0436   0.240628
24      HALLMARK_INFLAMMATORY_RESPONSE -0.507190       0.0123   0.269030
26  HALLMARK_INTERFERON_GAMMA_RESPONSE -0.622360       0.0277   0.177217
44    HALLMARK_TNFA_SIGNALING_VIA_NFKB -0.497607       0.0229   0.050620

In [18]:
# the pathway got inconsistent, only GSEA_pvalue pass the 0.05
print("those pathways that only pass T2_p_value: ", len(df[((df['GSEA_pvalue'] >= 0.05) & (df['T2_pvalue'] <= 0.05))]))
df[(df['GSEA_pvalue'] >= 0.05) & (df['T2_pvalue'] <= 0.05)]

those pathways that only pass T2_p_value:  30

                                     Pathway    Max_ES  GSEA_pvalue  T2_pvalue
0                      HALLMARK_ADIPOGENESIS  0.140921       0.9915   0.009484
2                 HALLMARK_ANDROGEN_RESPONSE  0.215851       0.6307   0.009339
3                      HALLMARK_ANGIOGENESIS  0.339709       0.3725   0.003811
4                   HALLMARK_APICAL_JUNCTION -0.340239       0.0833   0.011741
5                    HALLMARK_APICAL_SURFACE -0.350776       0.1753   0.008937
6                         HALLMARK_APOPTOSIS -0.276762       0.1850   0.003044
11                       HALLMARK_DNA_REPAIR  0.354455       0.0763   0.000288
12                      HALLMARK_E2F_TARGETS  0.357506       0.4494   0.006782
14          HALLMARK_ESTROGEN_RESPONSE_EARLY  0.242590       0.5770   0.001002
15           HALLMARK_ESTROGEN_RESPONSE_LATE -0.171938       0.9092   0.044917
17                   HALLMARK_G2M_CHECKPOINT  0.293459       0.5061   0.000512
18                       HALLMARK_GLYCOLYSIS  0.174931       0.8944   0.011455
19               HALLMARK_HEDGEHOG_SIGNALING -0.327190       0.2904   0.037204
20                  HALLMARK_HEME_METABOLISM -0.234262       0.2387   0.034120
21                          HALLMARK_HYPOXIA -0.284107       0.2652   0.011225
25        HALLMARK_INTERFERON_ALPHA_RESPONSE -0.621516       0.0809   0.015010
29                  HALLMARK_MITOTIC_SPINDLE -0.201958       0.6946   0.003735
31                   HALLMARK_MYC_TARGETS_V1  0.175868       0.9062   0.026083
34                  HALLMARK_NOTCH_SIGNALING  0.224445       0.8137   0.000485
37              HALLMARK_PANCREAS_BETA_CELLS -0.196180       0.9295   0.004411
38                       HALLMARK_PEROXISOME  0.181207       0.9031   0.000019
39          HALLMARK_PI3K_AKT_MTOR_SIGNALING -0.335329       0.0586   0.003357
40                HALLMARK_PROTEIN_SECRETION  0.397420       0.0740   0.000721
41  HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY -0.219764       0.7656   0.013921
42                  HALLMARK_SPERMATOGENESIS  0.222677       0.6395   0.000614
43               HALLMARK_TGF_BETA_SIGNALING -0.305482       0.4126   0.001740
45        HALLMARK_UNFOLDED_PROTEIN_RESPONSE -0.237909       0.5439   0.000384
46                   HALLMARK_UV_RESPONSE_DN -0.254590       0.4441   0.022124
48       HALLMARK_WNT_BETA_CATENIN_SIGNALING -0.319926       0.3771   0.002231
49            HALLMARK_XENOBIOTIC_METABOLISM -0.245207       0.3038   0.002650

In [19]:
print("those pathways that pass both: ", len(df[((df['GSEA_pvalue'] <= 0.05) & (df['T2_pvalue'] <= 0.05))]))

those pathways that pass both:  4